/*
# Storage policies for job-assets bucket

## Summary
Creates RLS policies on the `job-assets` storage bucket so authenticated users
can upload, read, and delete job photos and signatures. The bucket is private
(not publicly accessible), so reads use signed URLs generated by the frontend.

## Security
- SELECT (read): any authenticated user can list/download objects.
- INSERT (upload): any authenticated user can upload objects.
- UPDATE: any authenticated user can update objects.
- DELETE: any authenticated user can delete objects.
- Unauthenticated (anon) users have no access — the bucket is private.
*/

CREATE POLICY "job_assets_select_authenticated" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'job-assets');

CREATE POLICY "job_assets_insert_authenticated" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'job-assets');

CREATE POLICY "job_assets_update_authenticated" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'job-assets') WITH CHECK (bucket_id = 'job-assets');

CREATE POLICY "job_assets_delete_authenticated" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'job-assets');
